---
- name: Download Chrome
  become: false
  get_url:
    url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    dest: $HOME

- name: saved currnet user
  become: false
  shell: whoami
  register: current_user
  changed_when: false

- name: Install Chrome
  apt:
    deb: "/home/{{ current_user.stdout }}/google-chrome-stable_current_amd64.deb"

- name: Check if vagrant exists
  stat:
    path: /usr/bin/vagrant
  register: vagrant_bin

- name: Install Vagrant
  shell: |
    wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
    echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
    sudo apt update && sudo apt install vagrant
  when: not vagrant_bin.stat.exists

- name: install apps
  apt:
    pkg:
      - remmina
      - default-jre
